### ISSUE TITLE
Untrack test-generated config files

### ISSUE THREAD

**Issue by BrandonLMorris** [orlandoacevedo/MCGPU#35]
It seems that the tests automatically generate the config files for the simulations, but then never remove them. Is there a reason for keeping them around? I'm pretty sure they're untracked in git, since a lot of them in the repo still have Francis's home path in them.

Files like: `test/unittest/MultipleSolvents/meohtip3Tests/meohtip3MulSolvent.config`

If they're helpful, we can just remove them from the repo. Otherwise we can have the tests clean up after themselves.

**Comment by joverbey** [comment]
I believe Mitch was using some of those files to re-run specific tests, which is why they're not deleted automatically.

How about removing the config files from the repo but leaving the pattern(s) in .gitignore?  Then, we can leave the config files around, but they won't show up as modified (which is annoying).

**Comment by BrandonLMorris** [comment]
gtest has the ability to run specific tests individually. For instance, running the WaterTest would be

`./metrotest --gtest_filter=WaterTest.*`

But I agree, it's probably more sensible to just keep them around.
